# Generated by Django 3.1.7 on 2021-04-17 10:02

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('seats', models.PositiveIntegerField()),
                ('description', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='TourGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallerry')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.tour')),
            ],
        ),
    ]
