# Generated by Django 3.2.2 on 2021-05-09 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20210509_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.AddField(
            model_name='bookingorders',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingorders',
            name='payment_method',
            field=models.CharField(choices=[('pp', 'PayPal'), ('cc', 'Credit Card'), ('bt', 'Bank Transfer')], default='bt', max_length=2),
        ),
        migrations.AddField(
            model_name='bookingorders',
            name='status',
            field=models.CharField(choices=[('ok', 'confirmed'), ('ko', 'canceled'), ('pg', 'pending')], default='pg', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('ok', 'PAID'), ('ko', 'UNPAID')], default='ko', max_length=2),
        ),
    ]
