# Generated by Django 3.2.2 on 2021-05-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_bookingorders_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorders',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='agent.payment'),
        ),
    ]
