# Generated by Django 3.2.2 on 2021-05-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_alter_bookingorders_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingorders',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction',
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(default='ff', max_length=400),
            preserve_default=False,
        ),
    ]
