# Generated by Django 3.2.2 on 2021-05-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_tour_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(default=0, max_length=5)),
                ('review', models.TextField()),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('published', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='feedbacks',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='views',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='feedback',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.tour'),
        ),
    ]
